// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmjlrjnltoicjctncupr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptamxyam5sdG9pY2pjdG5jdXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NDgzODgsImV4cCI6MjA2MjMyNDM4OH0.N3quf0kXst3VpWJhX5ol2D6v6vNywAfs6JPgWdR2n6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);